.\" $Id$
.\"
.\" Man page for the dmtxquery utility (libdmtx project).
.\"
.\" To view: $ groff -man -T ascii dmtxquery.1 | less
.\" To text: $ groff -man -T ascii dmtxquery.1 | col -b | expand
.\"
.TH DMTXREAD 1 "June XX, 2008"
.SH NAME
dmtxquery \- extract information from dmtxread output
.SH SYNOPSIS
.B dmtxquery
\fIPROPERTY\fP [\fIOPTION\fP]... [\fIFILE\fP]...
.SH DESCRIPTION
dmtxquery extracts information from the XML output from dmtxread for individual or grouped barcode scan results.
.SH OPTIONS
.TP
\fB\-c\fP, \fB\-\-codewords\fP
Only print the codewords extracted from a Data Matrix, and not the actual decoded message.
.TP
\fB\-v\fP, \fB\-\-verbose\fP
Use verbose messages.
.TP
\fB\-V\fP, \fB\-\-version\fP
Print program version information.
.TP
\fB\-\-help\fP
Display this help message and quit.
.SH STANDARDS
ISO/IEC 16022:2000
.PP
ANSI/AIM BC11 ISS
.SH BUGS
Email bug reports to \fImike@dragonflylogic.com\fP
.SH AUTHOR
Copyright (c) 2008 Mike Laughton
.\" end of man page
