.\" $Id$
.\"
.\" Man page for the dmtxwrite utility (libdmtx project).
.\"
.\" To view: $ groff -man -T ascii dmtxwrite.1 | less
.\" To text: $ groff -man -T ascii dmtxwrite.1 | col -b | expand
.\"
.TH DMTXWRITE 1 "September 4, 2009"
.SH NAME
dmtxwrite \- create Data Matrix barcodes
.SH SYNOPSIS
.B dmtxwrite
[\fIOPTION\fP]... [FILE]
.SH DESCRIPTION
\fBdmtxwrite\fP encodes data from a file or standard input, and writes the resulting ECC200 Data Matrix barcode as an image.
.SH OPTIONS
.TP
\fB\-c\fP, \fB\-\-codewords\fP
Print codeword listing instead of creating barcode.
.TP
\fB\-d\fP, \fB\-\-module\fP=\fIN\fP
Module size in pixels.
.TP
\fB\-m\fP, \fB\-\-margin\fP=\fIN\fP
Margin size in pixels.
.TP
\fB\-e\fP, \fB\-\-encoding\fP=[bfactxe8]
Encodation scheme.
   b = Best optimized   best possible optimization (beta)
   f = Fast optimized   basic optimization (not implemented)
   a = ASCII  [default] ASCII standard & extended
   c = C40              digits and uppercase
   t = Text             digits and lowercase
   x = X12              ANSI X12 EDI
   e = EDIFACT          ASCII values 32-94
   8 = Base 256         all byte values 0-255
.TP
\fB\-f\fP, \fB\-\-format\fP=\fIFORMAT\fP
Output image format (PNG [default], TIF, GIF, PDF, etc...).
.TP
\fB\-l\fP, \fB\-\-list-formats\fP
List available image formats.
.TP
\fB\-o\fP, \fB\-\-output\fP=\fIFILE\fP
Barcode output filename. Default is standard output.
.TP
\fB\-p\fP, \fB\-\-preview\fP
Print ASCII art preview to standard output.
.TP
\fB\-r\fP, \fB\-\-resolution\fP=\fIN\fP
Set image print resolution (dpi).
.TP
\fB\-s\fP, \fB\-\-symbol-size\fP=[sr|RxC] (default "s")
  Automatic symbol size options:
    s = Auto square         r = Auto rectangle
  Manual symbol size options for square symbols:
    10x10   12x12   14x14   16x16   18x18   20x20
    22x22   24x24   26x26   32x32   36x36   40x40
    44x44   48x48   52x52   64x64   72x72   80x80
    88x88   96x96 104x104 120x120 132x132 144x144
  Manually symbol size options for rectangle symbols:
     8x18    8x32   12x26   12x36   16x36   16x48
.TP
\fB\-C\fP, \fB\-\-color\fP=\fICOLOR\fP
Barcode color (not implemented).
.TP
\fB\-B\fP, \fB\-\-bg-color\fP=\fICOLOR\fP
Background color (not implemented).
.TP
\fB\-M\fP, \fB\-\-mosaic\fP
Create non-standard Data Mosaic barcode.
.TP
\fB\-R\fP, \fB\-\-rotate\fP=\fIDEGREES\fP
Rotation angle in degrees (not implemented).
.TP
\fB\-v\fP, \fB\-\-verbose\fP
Use verbose messages.
.TP
\fB\-V\fP, \fB\-\-version\fP
Print program version information.
.TP
\fB\-\-help\fP
Display this help message and quit.
.SH STANDARDS
ISO/IEC 16022:2000
.PP
ANSI/AIM BC11 ISS
.SH BUGS
Email bug reports to \fImike@dragonflylogic.com\fP
.SH AUTHOR
Copyright (C) 2008, 2009 Mike Laughton
.\" end of man page
