.\" $Id$
.\"
.\" Man page for the dmtxwrite utility (libdmtx project).
.\"
.\" To view: $ groff -man -T ascii dmtxwrite.1 | less
.\" To text: $ groff -man -T ascii dmtxwrite.1 | col -b | expand
.\"
.TH DMTXWRITE 1 "April 13, 2008"
.SH NAME
dmtxwrite \- create Data Matrix barcodes
.SH SYNOPSIS
.B dmtxwrite
[\fIOPTION\fP]... [FILE]
.SH DESCRIPTION
dmtxwrite encodes data from a file or STDIN, and writes the resulting ECC200 Data Matrix barcode as an image.
.SH OPTIONS
.TP
\fB\-c\fP, \fB\-\-color\fP=\fICOLOR\fP
Barcode color. (not implemented yet)
.TP
\fB\-b\fP, \fB\-\-bg-color\fP=\fICOLOR\fP
Background color. (not implemented yet)
.TP
\fB\-d\fP, \fB\-\-module\fP=\fINUM\fP
Module size. (in pixels)
.TP
\fB\-m\fP, \fB\-\-margin\fP=\fINUM\fP
Margin size. (in pixels)
.TP
\fB\-e\fP, \fB\-\-encoding\fP=[bfactxe8]
Encodation scheme.
   b = Best optimized   best possible optimization (beta)
   f = Fast optimized   basic optimization (not implemented)
   a = ASCII  [default] ASCII standard & extended
   c = C40              digits and uppercase
   t = Text             digits and lowercase
   x = X12              ANSI X12 EDI
   e = EDIFACT          ASCII values 32-94
   8 = Base 256         all byte values 0-255
.TP
\fB\-f\fP, \fB\-\-format\fP=[npm]
Barcode output format.
   n = None             do not create barcode image
   p = PNG    [default] PNG image
   m = PNM              PNM image
.TP
\fB\-o\fP, \fB\-\-output\fP=\fIFILE\fP
Barcode output filename.
.TP
\fB\-p\fP, \fB\-\-preview\fP=[ac]
Barcode preview (STDOUT).
   a = ASCII            ASCII-art representation
   c = Codewords        list data and error codewords
.TP
\fB\-r\fP, \fB\-\-rotate\fP=\fIDEGREES\fP
Rotation angle. (degrees) (not implemented)
.TP
\fB\-s\fP, \fB\-\-symbol-size\fP=\fISIZE\fP
Symbol size specified in Rows x Cols.
   Automatic \fISIZE\fP options:
      s = Auto square  [default]
      r = Auto rectangle
   Manually specified \fISIZE\fP options for square symbols:
      10x10,  12x12,   14x14,   16x16,   18x18,   20x20,
      22x22,  24x24,   26x26,   32x32,   36x36,   40x40,
      44x44,  48x48,   52x52,   64x64,   72x72,   80x80,
      88x88,  96x96, 104x104, 120x120, 132x132, 144x144
   Manually specified \fISIZE\fP options for rectangular symbols:
       8x18,   8x32,   12x26,   12x36,   16x36,   16x48
.TP
\fB\-M\fP, \fB\-\-mosaic\fP
Create non-standard Data Mosaic barcode.
.TP
\fB\-R\fP, \fB\-\-resolution\fP=\fINUM\fP
Set image print resolution (dpi).
.TP
\fB\-v\fP, \fB\-\-verbose\fP
Use verbose messages.
.TP
\fB\-V\fP, \fB\-\-version\fP
Print program version information.
.TP
\fB\-\-help\fP
Display this help message and quit.
.SH STANDARDS
ISO/IEC 16022:2000
.PP
ANSI/AIM BC11 ISS
.SH BUGS
Email bug reports to \fImike@dragonflylogic.com\fP
.SH AUTHOR
Copyright (c) 2008 Mike Laughton
.\" end of man page
