.\" $Id: dmtxread.1,v 1.3 2006-10-15 19:39:08 mblaughton Exp $
.\"
.\" Man page for the dmtxread utility (libdmtx project).
.\"
.\" $ groff -man -T ascii dmtxread.1
.\"
.TH DMTXREAD 1 "October 15, 2006"
.SH NAME
dmtxread \- read data matrix barcodes contained in images
.SH SYNOPSIS
\fBdmtxread\fP [\fIoptions\fP] [\fIFILE\fP...]

.SH DESCRIPTION
Dmtxread decodes data matrix barcodes found in PNG or TIFF images and writes the decoded message to standard output.

.SH OPTIONS
 \fB-c\fP, \fB--count\fP=\fINUM\fP
        Stop after finding \fINUM\fP barcodes (not implemented yet)

 \fB-v\fP, \fB--vertical\fP=\fINUM\fP
        Use \fINUM\fP vertical scan lines in scan pattern

 \fB-h\fP, \fB--horizontal\fP=\fINUM\fP
        Use \fINUM\fP horizontal scan lines in scan pattern

 \fB-n\fP, \fB--page-number\fP
        Print page number with each decoded message

     \fB--help\fP
        Display help message and quit

.SH BUGS
Email bug reports to \fImike@dragonflylogic.com\fP

.SH AUTHOR
Copyright (C) 2006 Mike Laughton

.\" end of man page
